def fibonacci(stopValue):
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    """
    ans = 0
    fib = [1,2]
    while fib[-1] < stopValue+1:
        if fib[-1]%2 == 0:
            ans += fib[-1]
        fib.append(fib[-1] + fib[-2])
    
    return ans